### ISSUE TITLE
[RULE] wrap all scopes in {}

### ISSUE THREAD

**Issue by AdriVanHoudt** [cjihrig/eslint-plugin-hapi#1]
see http://hapijs.com/styleguide#user-content-scope

**Comment by cjihrig** [comment]
Isn't this already handled by http://eslint.org/docs/rules/curly

**Comment by AdriVanHoudt** [comment]
looks like it

**Comment by AdriVanHoudt** [comment]
but it is disabled in the default config of lab however

**Comment by cjihrig** [comment]
@geek any reason it's turned off by default in lab?

**Comment by AdriVanHoudt** [comment]
Luckily there is http://goatslacker.github.io/fixmyjs.com/ to fix this for me :D

**Comment by cjihrig** [comment]
Yea. It would be much better if everything was taken care of in one place (lab) though.

**Comment by AdriVanHoudt** [comment]
yeah ofc the fixmyjs is just so I don't have to edit 800 lines again ;)

**Comment by geek** [comment]
@cjihrig just published lab with this rule.  Please try in lab 5.6.0

**Comment by AdriVanHoudt** [comment]
@geek cool, will update modules tomorrow and check if everything works. Also is there a reason `no-undef` is 0 ?

**Comment by geek** [comment]
We can try enabling `no-undef`, in the beginning I tried to keep it only somewhat opinionated, which is why this rule wasn't enforced since we already had global checking.

**Comment by AdriVanHoudt** [comment]
yeah, maybe add it as a warning first, I do fear a lot of unused `internals` will be flagged

**Comment by AdriVanHoudt** [comment]
@geek updated all my public modules (4 :D) and works like a charm, maybe open up a discussion somewhere (hapi/contrib?) to discuss all the rules?
