### ISSUE TITLE
One-liner functions

### ISSUE THREAD

**Issue by Marsup** [cjihrig/eslint-plugin-hapi#2]
Hi,

I'm getting a lot of errors for one-liner functions because there's no line break, and I'd say it's quite fine.
What do you think ?

**Comment by AdriVanHoudt** [comment]
you mean for `function () {}`?

**Comment by Marsup** [comment]
Yes.

**Comment by AdriVanHoudt** [comment]
`hapi-scope-start` should check empty function bodies (or you could use Hoek.ignore :P)

**Comment by Marsup** [comment]
I don't mean empty, I mean one liner...

**Comment by AdriVanHoudt** [comment]
but then `function () { console.log('a') }` would also be valid?

**Comment by Marsup** [comment]
For me it should, I don't see any value in line break if there's a single instruction.

**Comment by Marsup** [comment]
Btw sorry, it's the wrong repo, I should have put this issue in hapi-scope-start, tell me and I'll move it.

**Comment by AdriVanHoudt** [comment]
ok what about `function () { console.log('a'); console.log('b'); }`?

**Comment by Marsup** [comment]
Probably not. I was thinking about the equivalent of ES6 fat arrow w/o block scope.

**Comment by cjihrig** [comment]
I'll work on a fix.

**Comment by Marsup** [comment]
Considering my current warnings, what about allowing this for functions with a single return instruction ?

**Comment by cjihrig** [comment]
My plan was to determine the line number of the end of the function. If it's the same as the beginning line, then don't enforce the rule.

**Comment by Marsup** [comment]
Like @AdriVanHoudt said, I'm not sure it should apply to multi statements functions, but the styleguide doesn't tell about this specifically.

**Comment by AdriVanHoudt** [comment]
I can see the value in not enforcing for a single statement but with multiple statements it should error

**Comment by cjihrig** [comment]
Any opinion from @hueniverse or @geek?

**Comment by geek** [comment]
I like to keep it consistent and apply the same rule to shorter functions.  Mainly because it is now easier to identify new scopes and function declarations with that extra line formatting.

**Comment by danielb2** [comment]
What @geek said. I'm generally not in favor of on-liners as it opens the door to developers to endlessly tacking on things to the one-line function because they're too lazy to break it out and format it correctly.

It's the same as one-liners for if statements (especially omitting the braces)

**Comment by Marsup** [comment]
OK, I'll fix my warnings then, thanks for the feedback.
